language: go
go_import_path: github.com/rmasclef/healthcheck
go:
  - 1.11.x

sudo: false

install:
  - go get -u github.com/golang/dep/cmd/dep
    && dep ensure -vendor-only -v

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
